# Generated by Django 4.0 on 2022-12-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefered_type',
            field=models.CharField(choices=[('voice', 'voice'), ('text', 'text')], max_length=50, null=True),
        ),
    ]
