# Generated by Django 4.0 on 2022-12-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_user_prefered_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prefered_type',
        ),
    ]
