# Generated by Django 4.0 on 2022-12-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
