# Generated by Django 4.0 on 2022-12-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.AddField(
            model_name='room',
            name='phone',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
